=== nuke-build/nuke/source/Nuke.CodeGeneration/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "title": "Tool metadata schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "noExtensionMethods": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "noArguments": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "name",
        "properties"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "assertion": {
          "description": "Automatic assertion.",
          "type": "string",
          "enum": [
            "NotNull",
            "File",
            "Directory",
            "FileOrNull",
            "DirectoryOrNull"
          ]
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "noExtensionMethod": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "noExtensionMethods": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "noArguments": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "properties"
      ]
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        }
      },
      "required": [
        "settingsClass"
      ]
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "license": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "packageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "environmentExecutable": {
      "description": "Exact name of the environment variable that contains the path to the executable.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    }
  },
  "required": [
    "name",
    "officialUrl",
    "tasks"
  ]
}

=== nuke-build/nuke/source/Nuke.Common/Tools/Netlify/Netlify.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.Tooling.Generator/schema.json",
  "name": "Netlify",
  "officialUrl": "https://docs.netlify.com/cli/get-started/",
  "help": "Netlify’s command line interface (CLI) lets you configure <a href=\"https://docs.netlify.com/cli/get-started/#continuous-deployment\">continuous deployment</a> straight from the command line. You can use Netlify CLI to <a href=\"https://docs.netlify.com/cli/get-started/#run-a-local-development-environment\">run a local development server</a> that you can share with others, <a href=\"https://docs.netlify.com/cli/get-started/#run-builds-locally\">run a local build and plugins</a>, and <a href=\"https://docs.netlify.com/cli/get-started/#manual-deploys\">deploy your site</a>.",
  "pathExecutable": "npx",
  "tasks": [
    {
      "postfix": "Deploy",
      "definiteArgument": "netlify deploy",
      "settingsClass": {
        "properties": [
          {
            "name": "Directory",
            "type": "string",
            "format": "--dir {value}",
            "help": "Specify a folder to deploy."
          },
          {
            "name": "Functions",
            "type": "string",
            "format": "--functions {value}",
            "help": "Specify a functions folder to deploy."
          },
          {
            "name": "Production",
            "type": "bool",
            "format": "--prod",
            "help": "Deploy to production."
          },
          {
            "name": "ProductionIfUnlocked",
            "type": "bool",
            "format": "--prodIfUnlocked",
            "help": "Deploy to production if unlocked, create a draft otherwise."
          },
          {
            "name": "Alias",
            "type": "string",
            "format": "--alias {value}",
            "help": "Specifies the alias for deployment, the string at the beginning of the deploy subdomain. Useful for creating predictable deployment URLs. Avoid setting an alias string to the same value as a deployed branch. <code>alias doesn’t</code> create a branch deploy and can’t be used in conjunction with the branch subdomain feature. Maximum 37 characters."
          },
          {
            "name": "Branch",
            "type": "string",
            "format": "--branch {value}",
            "help": "Serves the same functionality as --alias. Deprecated and will be removed in future versions."
          },
          {
            "name": "Open",
            "type": "bool",
            "format": "--open",
            "help": "Open site after deploy."
          },
          {
            "name": "Message",
            "type": "string",
            "format": "--message {value}",
            "help": "A short message to include in the deploy log."
          },
          {
            "name": "Auth",
            "type": "string",
            "format": "--auth {value}",
            "secret": true,
            "help": "Netlify auth token to deploy with."
          },
          {
            "name": "Site",
            "type": "string",
            "format": "--site {value}",
            "help": "Netlify auth token to deploy with."
          },
          {
            "name": "Json",
            "type": "bool",
            "format": "--json",
            "help": "Output deployment data as JSON."
          },
          {
            "name": "Timeout",
            "type": "string",
            "format": "--timeout {value}",
            "help": "Timeout to wait for deployment to finish."
          },
          {
            "name": "Trigger",
            "type": "bool",
            "format": "--trigger",
            "help": "Trigger a new build of your site on Netlify without uploading local files."
          },
          {
            "name": "Build",
            "type": "bool",
            "format": "--build",
            "help": "Run build command before deploying."
          }
        ]
      }
    },
    {
      "postfix": "SitesCreate",
      "returnType": "string",
      "definiteArgument": "netlify sites:create",
      "settingsClass": {
        "properties": [
          {
            "name": "Name",
            "type": "string",
            "format": "--name {value}",
            "help": "Name of site."
          },
          {
            "name": "AccountSlug",
            "type": "string",
            "format": "--account-slug {value}",
            "help": "Account slug to create the site under."
          },
          {
            "name": "WithCI",
            "type": "bool",
            "format": "--with-ci",
            "help": "Initialize CI hooks during site creation."
          },
          {
            "name": "Manual",
            "type": "bool",
            "format": "--manual",
            "help": "Force manual CI setup. Used <code>--with-ci</code> flag."
          }
        ]
      }
    },
    {
      "postfix": "SitesDelete",
      "definiteArgument": "netlify sites:delete",
      "settingsClass": {
        "properties": [
          {
            "name": "SiteId",
            "type": "string",
            "format": "{value}",
            "help": "Site ID to delete."
          },
          {
            "name": "Force",
            "type": "bool",
            "format": "--force",
            "help": "Delete without prompting (useful for CI)."
          }
        ]
      }
    }
  ],
  "commonTaskProperties": [
    {
      "name": "Debug",
      "type": "bool",
      "format": "--debug",
      "help": "Print debugging information."
    },
    {
      "name": "HttpProxy",
      "type": "string",
      "format": "--httpProxy {value}",
      "help": "Proxy server address to route requests through."
    },
    {
      "name": "HttpProxyCertificateFileName",
      "type": "string",
      "format": "--httpProxyCertificateFilename {value}",
      "help": "Certificate file to use when connecting using a proxy server."
    }
  ]
}

=== nuke-build/nuke/build/specifications/Xunit.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "license": [
    "Copyright Matthias Koch 2017.",
    "Distributed under the MIT License.",
    "https://github.com/nuke-build/tools/blob/master/LICENSE"
  ],
  "references": [
    "https://raw.githubusercontent.com/xunit/xunit/master/src/xunit.console/ConsoleRunner.cs"
  ],
  "name": "Xunit",
  "officialUrl": "https://xunit.github.io",
  "help": "xUnit.net is a free, open source, community-focused unit testing tool for the .NET Framework. Written by the original inventor of NUnit v2, xUnit.net is the latest technology for unit testing C#, F#, VB.NET and other .NET languages. xUnit.net works with ReSharper, CodeRush, TestDriven.NET and Xamarin. It is part of the <a href=\"https://www.dotnetfoundation.org/\">.NET Foundation</a>, and operates under their <a href=\"https://www.dotnetfoundation.org/code-of-conduct\">code of conduct</a>. It is licensed under <a href=\"https://opensource.org/licenses/Apache-2.0\">Apache 2</a> (an OSI approved license).",
  "packageId": "xunit.runner.console",
  "tasks": [
    {
      "postfix": "2",
      "customAssertion": true,
      "settingsClass": {
        "properties": [
          {
            "name": "TargetAssemblyWithConfigs",
            "type": "LookupTable<string, string>",
            "format": "{value}",
            "itemFormat": "{key} {value}",
            "help": "Assemblies to test, and their related related configuration files (ending with .json or .config)."
          },
          {
            "name": "NoLogo",
            "type": "bool",
            "format": "-nologo",
            "help": "Do not show the copyright message."
          },
          {
            "name": "NoColor",
            "type": "bool",
            "format": "-nocolor",
            "help": "Do not output results with colors."
          },
          {
            "name": "FailSkips",
            "type": "bool",
            "format": "-failskips",
            "help": "Convert skipped tests into failures."
          },
          {
            "name": "StopOnFail",
            "type": "bool",
            "format": "-stoponfail",
            "help": "Stop on first test failure."
          },
          {
            "name": "Parallel",
            "type": "Xunit2ParallelOption",
            "format": "-parallel {value}",
            "help": "Set parallelization based on option:<ul><li><b>none:</b> turn off all parallelization</li><li><b>collections:</b> only parallelize collections</li><li><b>assemblies:</b> only parallelize assemblies</li><li><b>all:</b> parallelize assemblies &amp; collections</li></ul>"
          },
          {
            "name": "MaxThreads",
            "type": "int",
            "format": "-maxthreads {value}",
            "help": "Maximum thread count for collection parallelization:<br/><ul><li><b>default:</b> run with default (1 thread per CPU thread)</li><li><b>unlimited:</b> run with unbounded thread count</li><li><b>(number):</b> limit task thread pool size to 'count'</li></ul>"
          },
          {
            "name": "AppDomainMode",
            "type": "Xunit2AppDomainMode",
            "format": "-appdomains {value}",
            "help": "AppDomain modes:<ul><li><c>-ifavailable</c>: choose based on library type</li><li><c>-required</c>: force app domains on</li><li><c>-denied</c>: force app domains off</li></ul>"
          },
          {
            "name": "NoShadowCopying",
            "type": "bool",
            "format": "-noshadow",
            "help": "Do not shadow copy assemblies."
          },
          {
            "name": "Wait",
            "type": "bool",
            "format": "-wait",
            "help": "Wait for input after completion."
          },
          {
            "name": "Diagnostics",
            "type": "bool",
            "format": "-diagnostics",
            "help": "Enable diagnostics messages for all test assemblies."
          },
          {
            "name": "Pause",
            "type": "bool",
            "format": "-pause",
            "help": "Pause before doing any work, to help attach a debugger."
          },
          {
            "name": "Debug",
            "type": "bool",
            "format": "-debug",
            "help": "Launch the debugger to debug the tests."
          },
          {
            "name": "Serialization",
            "type": "bool",
            "format": "-serialize",
            "help": "Serialize all test cases (for diagnostic purposes only)."
          },
          {
            "name": "Traits",
            "type": "LookupTable<string, string>",
            "format": "-trait {value}",
            "itemFormat": "{key}={value}",
            "help": "Only run tests with matching name/value traits."
          },
          {
            "name": "ExcludedTraits",
            "type": "LookupTable<string, string>",
            "format": "-notrait {value}",
            "itemFormat": "{key}={value}",
            "help": "Do not run tests with matching name/value traits."
          },
          {
            "name": "Methods",
            "type": "List<string>",
            "format": "-method {value}",
            "help": "Run a given test method (can be fully specified or use a wildcard; i.e., 'MyNamespace.MyClass.MyTestMethod' or '*.MyTestMethod')."
          },
          {
            "name": "Classes",
            "type": "List<string>",
            "format": "-class {value}",
            "help": "Run all methods in a given test class (should be fully specified; i.e., 'MyNamespace.MyClass')."
          },
          {
            "name": "Namespaces",
            "type": "List<string>",
            "format": "-namespace {value}",
            "help": "Run all methods in a given namespace (i.e., 'MyNamespace.MySubNamespace')."
          },
          {
            "name": "NoAutoReporters",
            "type": "bool",
            "format": "-noautoreporters",
            "help": "Do not allow reporters to be auto-enabled by environment for example, auto-detecting TeamCity or AppVeyor)."
          },
          {
            "name": "Reporter",
            "type": "Xunit2ReporterType",
            "format": "-{value}",
            "help": "Reporters:<ul><li><c>-appveyor</c>: forces AppVeyor CI mode (normally auto-detected)</li><li><c>-json</c>: show progress messages in JSON format</li><li><c>-quiet</c>: do not show progress messages</li><li><c>-teamcity</c>: forces TeamCity mode (normally auto-detected)</li><li><c>-verbose</c>: show verbose progress messages</li></ul>"
          },
          {
            "name": "ResultReports",
            "type": "Dictionary<Xunit2ResultFormat, string>",
            "format": "-{value}",
            "itemFormat": "{key} {value}",
            "help": "Result formats:<ul><li><c>-xml</c>: output results to xUnit.net v2 XML file</li><li><c>-xmlv1</c>: output results to xUnit.net v1 XML file</li><li><c>-nunit</c>: output results to NUnit v2.5 XML file</li><li><c>-html</c>: output results to HTML file</li></ul>"
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "Xunit2ReporterType",
      "values": [
        "AppVeyor",
        "JSON",
        "Quiet",
        "TeamCity",
        "Verbose"
      ]
    },
    {
      "name": "Xunit2ResultFormat",
      "values": [
        "Xml",
        "XmlV1",
        "NUnit",
        "HTML"
      ]
    },
    {
      "name": "Xunit2ParallelOption",
      "values": [
        "None",
        "Collections",
        "Assemblies",
        "All"
      ]
    },
    {
      "name": "Xunit2AppDomainMode",
      "values": [
        "IfAvailable",
        "Required",
        "Denied"
      ]
    }
  ]
}

=== nuke-build/nuke/build/specifications/TestCloud.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "license": [
    "Copyright Matthias Koch 2017.",
    "Distributed under the MIT License.",
    "https://github.com/nuke-build/tools/blob/master/LICENSE"
  ],
  "references": [
    "https://developer.xamarin.com/guides/testcloud/uitest/working-with/submitting-tests-at-command-line#//div[@class='doc-content']/table"
  ],
  "name": "TestCloud",
  "officialUrl": "https://developer.xamarin.com/guides/testcloud/",
  "help": "Test Cloud is a cloud based service consisting of thousands of physical mobile devices. Users upload their apps and tests to Test Cloud, which will install the apps on the devices and run the tests. When the tests are complete, Test Cloud, the results made available to users through an easy to use and informative web-based front end.",
  "packageId": "Xamarin.UITest",
  "packageExecutable": "test-cloud.exe",
  "tasks": [
    {
      "definiteArgument": "submit",
      "settingsClass": {
        "properties": [
          {
            "name": "AssemblyDirectory",
            "type": "string",
            "format": "--assembly-dir {value}",
            "help": "The path to the folder holding the test assemblies."
          },
          {
            "name": "Devices",
            "type": "string",
            "format": "--devices {value}",
            "help": "The device ID that was provided in the Test Cloud Upload dialog."
          },
          {
            "name": "UserEmail",
            "type": "string",
            "format": "--user {value}",
            "help": "The e-mail address of the team member submitting the tests."
          },
          {
            "name": "NunitResultsFile",
            "type": "string",
            "format": "--nunit-xml {value}",
            "help": "The filename to which test results are exported, formatted as NUnit results XML. Optional."
          },
          {
            "name": "SignInfoFile",
            "type": "string",
            "format": "--sign-info {value}",
            "help": "Android only. Supply a signing information file that will be used to sign the Test Server APK. See the section below for more details. Optional."
          },
          {
            "name": "DsymFile",
            "type": "string",
            "format": "--dsym {value}",
            "help": "iOS only. Will upload the dSYM files along with the application and tests. This allows for more detail in the log files. Optional."
          },
          {
            "name": "Fixtures",
            "type": "List<string>",
            "format": "--fixture {value}",
            "help": "NUnit fixture / namespace to run. (Can be used multiple times)."
          },
          {
            "name": "IncludeCategories",
            "type": "List<string>",
            "format": "--include {value}",
            "help": "Identifies the NUnit test categories that should only be included in the test run."
          },
          {
            "name": "ExcludeCategories",
            "type": "List<string>",
            "format": "--exclude {value}",
            "help": "Identifies the NUnit test categories that should be excluded from the test run."
          },
          {
            "name": "TestChunk",
            "type": "bool",
            "format": "--test-chunk",
            "help": "Run tests in parallel by method."
          },
          {
            "name": "FixtureChunk",
            "type": "bool",
            "format": "--fixture-chunk",
            "help": "Run tests in parallel by fixture."
          },
          {
            "name": "DataPaths",
            "type": "List<string>",
            "format": "--data {value}",
            "help": "Uploads file or directory along with assemblies. (Can be used multiple times)."
          }
        ]
      }
    }
  ]
}

=== nuke-build/nuke/source/Nuke.Common/Tools/CorFlags/CorFlags.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.Tooling.Generator/schema.json",
  "name": "CorFlags",
  "officialUrl": "https://docs.microsoft.com/en-us/dotnet/framework/tools/corflags-exe-corflags-conversion-tool",
  "help": "The CorFlags Conversion tool allows you to configure the CorFlags section of the header of a portable executable image.",
  "pathExecutable": "CorFlags.exe",
  "tasks": [
    {
      "help": "The CorFlags Conversion tool allows you to configure the CorFlags section of the header of a portable executable image.",
      "settingsClass": {
        "properties": [
          {
            "name": "NoLogo",
            "type": "bool",
            "format": "-nologo",
            "help": "Suppresses the Microsoft startup banner display."
          },
          {
            "name": "UpgradeCLRHeader",
            "type": "bool",
            "format": "-UpgradeCLRHeader",
            "help": "Upgrades the CLR header version to 2.5. <em>Note</em>: Assemblies must have a CLR header version of 2.5 or greater to run natively."
          },
          {
            "name": "RevertCLRHeader",
            "type": "bool",
            "format": "-RevertCLRHeader",
            "help": "Reverts the CLR header version to 2.0."
          },
          {
            "name": "Force",
            "type": "bool",
            "format": "-Force",
            "help": "Forces an update even if the assembly is strong-named. <em>Important</em>: If you update a strong-named assembly, you must sign it again before executing its code."
          },
          {
            "name": "Assembly",
            "type": "string",
            "format": "{value}",
            "position": 1,
            "help": "The name of the assembly for which to configure the CorFlags."
          },
          {
            "name": "ILOnly",
            "type": "bool",
            "format": "-ILONLY{value}",
            "formatter": "FormatBoolean",
            "help": "Sets/clears the ILONLY flag."
          },
          {
            "name": "Require32Bit",
            "type": "bool",
            "format": "-32BIT{value}",
            "formatter": "FormatBoolean",
            "help": "Sets/clears the 32BITREQUIRED flag."
          },
          {
            "name": "Prefer32Bit",
            "type": "bool",
            "format": "-32BITPREF{value}",
            "formatter": "FormatBoolean",
            "help": "Sets/clears the 32BITPREFERRED flag."
          }
        ]
      }
    }
  ]
}
