=== nuke-build/nuke/source/Nuke.CodeGeneration/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "title": "Tool metadata schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "noExtensionMethods": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "noArguments": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "name",
        "properties"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "assertion": {
          "description": "Automatic assertion.",
          "type": "string",
          "enum": [
            "NotNull",
            "File",
            "Directory",
            "FileOrNull",
            "DirectoryOrNull"
          ]
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "noExtensionMethod": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "noExtensionMethods": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "noArguments": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "properties"
      ]
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        }
      },
      "required": [
        "settingsClass"
      ]
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "license": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "packageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "environmentExecutable": {
      "description": "Exact name of the environment variable that contains the path to the executable.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    }
  },
  "required": [
    "name",
    "officialUrl",
    "tasks"
  ]
}

=== nuke-build/nuke/build/specifications/Npm.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "license": [
    "Copyright Matthias Koch 2017.",
    "Distributed under the MIT License.",
    "https://github.com/nuke-build/tools/blob/master/LICENSE"
  ],
  "references": [
    "https://docs.npmjs.com/cli/install#//div[@id='page']",
    "https://docs.npmjs.com/cli/run-script#//div[@id='page']"
  ],
  "name": "Npm",
  "officialUrl": "https://www.npmjs.com/",
  "help": "npm is the package manager for the Node JavaScript platform. It puts modules in place so that node can find them, and manages dependency conflicts intelligently.<para/>It is extremely configurable to support a wide variety of use cases. Most commonly, it is used to publish, discover, install, and develop node programs.",
  "pathExecutable": "npm",
  "tasks": [
    {
      "help": "Installs a package, and any packages that it depends on. If the package has a package-lock or shrinkwrap file, the installation of dependencies will be driven by that, with an <b>npm-shrinkwrap.json</b> taking precedence if both files exist. See <a href=\"https://docs.npmjs.com/files/package-lock.json\">package-lock.json</a> and <a href=\"https://docs.npmjs.com/cli/shrinkwrap\">npm-shrinkwrap</a>.<para/>A package is: <ul><li>a) A folder containing a program described by a <a href=\"https://docs.npmjs.com/files/package.json\">package.json file</a></li><li>b) A gzipped tarball containing (b)</li><li>c) A url that resolves to (b)</li><li>d) a <c>&lt;name&gt;@&lt;version&gt;</c> that is published on the registry (see <a href=\"https://docs.npmjs.com/misc/registry\">npm-registry</a>) with (c)</li><li>e) a <c>&lt;name&gt;@&lt;tag&gt;</c> (see <a href=\"https://docs.npmjs.com/cli/dist-tag\">npm-dist-tag</a>) that points to (d)</li><li>f) a <c>&lt;name&gt;</c> that has a \"latest\" tag satisfying (e)</li><li>g) a <c>&lt;git remote url&gt;</c> that resolves to (a)</li></ul>",
      "postfix": "Install",
      "definiteArgument": "install",
      "settingsClass": {
        "properties": [
          {
            "name": "Packages",
            "type": "List<string>",
            "format": "{value}",
            "help": "List of packages to be installed."
          },
          {
            "name": "Production",
            "type": "bool",
            "format": "--production",
            "help": "Causes npm to not install modules listed in devDependencies."
          },
          {
            "name": "Force",
            "type": "bool",
            "format": "--force",
            "help": "Forces npm to fetch remote resources even if a local copy exists on disk."
          },
          {
            "name": "Global",
            "type": "bool",
            "format": "--global",
            "help": "Causes npm to install the package globally rather than locally. See <a href=\"https://docs.npmjs.com/files/folders\">npm-folders</a>."
          },
          {
            "name": "GlobalStyle",
            "type": "bool",
            "format": "--global-style",
            "help": "Causes npm to install the package into your local <c>node_modules</c> folder with the same layout it uses with the global <c>node_modules</c> folder. Only your direct dependencies will show in <c>node_modules</c> and everything they depend on will be flattened in their <c>node_modules</c> folders. This obviously will eliminate some deduping."
          },
          {
            "name": "IgnoreScripts",
            "type": "bool",
            "format": "--ignore-scripts",
            "help": "Causes npm to not execute any scripts defined in the package.json. See <a href=\"https://docs.npmjs.com/misc/scripts\">npm-scripts</a>."
          },
          {
            "name": "LegacyBundling",
            "type": "bool",
            "format": "--legacy-bundling",
            "help": "Causes npm to install the package such that versions of npm prior to 1.4, such as the one included with node 0.8, can install the package. This eliminates all automatic deduping."
          },
          {
            "name": "Link",
            "type": "bool",
            "format": "--link",
            "help": "Cause npm to link global installs into the local space in some cases."
          },
          {
            "name": "NoBinLinks",
            "type": "bool",
            "format": "--no-bin-links",
            "help": "Prevents npm from creating symlinks for any binaries the package might contain."
          },
          {
            "name": "NoOptional",
            "type": "bool",
            "format": "--no-optional",
            "help": "Prevents optional dependencies from being installed."
          },
          {
            "name": "NoShrinkWrap",
            "type": "bool",
            "format": "--no-shrinkwrap",
            "help": "Ignores an available shrinkwrap file and use the package.json instead."
          },
          {
            "name": "NodeDir",
            "type": "string",
            "format": "--nodedir={value}",
            "help": "Allows npm to find the node source code so that npm can compile native modules."
          },
          {
            "name": "Only",
            "type": "NpmOnlyMode",
            "format": "--only={value}",
            "help": "Causes either only <c>devDependencies</c> or only non-<c>devDependencies</c> to be installed regardless of the <c>NODE_ENV</c>."
          }
        ]
      }
    },
    {
      "help": "Runs an arbitrary command from a package's <c>\"scripts\"</c> object. If no <c>\"command\"</c> is provided, it will list the available scripts. <c>run[-script]</c> is used by the test, start, restart, and stop commands, but can be called directly, as well. When the scripts in the package are printed out, they're separated into lifecycle (test, start, restart) and directly-run scripts.\"",
      "postfix": "Run",
      "definiteArgument": "run",
      "settingsClass": {
        "properties": [
          {
            "name": "Command",
            "type": "string",
            "format": "{value}",
            "help": "The command to be executed."
          },
          {
            "name": "Arguments",
            "type": "List<string>",
            "format": "-- {value}",
            "separator": " ",
            "help": "Arguments passed to the script."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "NpmOnlyMode",
      "values": [
        "production",
        "development"
      ]
    }
  ]
}

=== nuke-build/nuke/source/Nuke.Common/Tools/Boots/Boots.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "references": [
    "https://github.com/jonathanpeppers/boots#systemcommandline"
  ],
  "name": "Boots",
  "officialUrl": "https://github.com/jonathanpeppers/boots",
  "help": "boots is a .NET global tool for <c>bootstrapping</c> <c>vsix</c> and <c>pkg</c> files.",
  "packageId": "Boots",
  "packageExecutable": "Boots.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Stable",
            "type": "BootsProductType",
            "format": "--stable {value}",
            "help": "Install the latest <em>stable</em> version of a product from VS manifests. Options include: <c>Xamarin.Android</c>, <c>Xamarin.iOS</c>, <c>Xamarin.Mac</c>, and <c>Mono</c>"
          },
          {
            "name": "Preview",
            "type": "BootsProductType",
            "format": "--preview {value}",
            "help": "Install the latest <em>preview</em> version of a product from VS manifests. Options include: <c>Xamarin.Android</c>, <c>Xamarin.iOS</c>, <c>Xamarin.Mac</c>, and <c>Mono</c>"
          },
          {
            "name": "Url",
            "type": "string",
            "format": "--url {value}",
            "help": "A Url to a <c>pkg</c> or <c>vsix</c> file to install"
          },
          {
            "name": "FileType",
            "type": "BootsFileType",
            "format": "--file-type {value}",
            "help": "Specifies the type of file to be installed such as <c>vsix</c>, <c>pkg</c>, or <c>msi</c>. Defaults to <c>vsix</c> on Windows and <c>pkg</c> on macOS"
          },
          {
            "name": "Timeout",
            "type": "int",
            "format": "--timeout {value}",
            "help": "Specifies a timeout for <c>HttpClient</c>. If omitted, uses the .NET default of 100 seconds"
          },
          {
            "name": "ReadWriteTimeout",
            "type": "int",
            "format": "--read-write-timeout {value}",
            "help": "Specifies a timeout for reading/writing from a <c>HttpClient</c> stream. If omitted, uses a default of 300 seconds"
          },
          {
            "name": "Retries",
            "type": "int",
            "format": "--retries {value}",
            "help": "Specifies a number of retries for <c>HttpClient</c> failures. If omitted, uses a default of 3 retries"
          },
          {
            "name": "Version",
            "type": "bool",
            "format": "--version",
            "help": "Show version information"
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "BootsProductType",
      "values": [
        "Mono",
        "Xamarin.Android",
        "Xamarin.iOS",
        "Xamarin.Mac"
      ]
    },
    {
      "name": "BootsFileType",
      "values": [
        "vsix",
        "pkg",
        "msi"
      ]
    }
  ]
}

=== nuke-build/nuke/build/specifications/Fixie.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "references": [
    "https://raw.githubusercontent.com/fixie/fixie/main/src/Fixie.Console/Program.cs"
  ],
  "name": "Fixie",
  "officialUrl": "https://fixie.github.io/",
  "help": "Fixie is a .NET modern test framework similar to NUnit and xUnit, but with an emphasis on low-ceremony defaults and flexible customization.",
  "packageId": "fixie.console",
  "packageExecutable": "dotnet-fixie.dll",
  "tasks": [
    {
      "help": "The <c>dotnet fixie</c> command is used to execute Fixie unit tests in a given project.",
      "settingsClass": {
        "properties": [
          {
            "name": "Configuration",
            "type": "string",
            "format": "--configuration {value}",
            "help": "The configuration under which to build. When this option is omitted, the default configuration is `Debug`."
          },
          {
            "name": "NoBuild",
            "type": "bool",
            "format": "--no-build",
            "help": "Skip building the test project prior to running it."
          },
          {
            "name": "Framework",
            "type": "string",
            "format": "--framework {value}",
            "help": "Only run test assemblies targeting a specific framework."
          },
          {
            "name": "Report",
            "type": "string",
            "format": "--report {value}",
            "help": "Write test results to the specified path, using the xUnit XML format."
          },
          {
            "name": "CustomArguments",
            "type": "string",
            "format": "-- {value}",
            "help": "Arbitrary arguments made available to custom discovery/execution classes."
          }
        ]
      }
    }
  ]
}

=== nuke-build/nuke/build/specifications/NerdbankGitVersioning.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "references": [
    "https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md"
  ],
  "name": "NerdbankGitVersioning",
  "officialUrl": "https://github.com/AArnott/Nerdbank.GitVersioning",
  "packageId": "nbgv",
  "packageExecutable": "nbgv.dll",
  "tasks": [
    {
      "help": "Prepares a project to have version stamps applied using Nerdbank.GitVersioning.",
      "postfix": "Install",
      "definiteArgument": "install",
      "settingsClass": {
        "properties": [
          {
            "name": "Path",
            "type": "string",
            "format": "--path {value}",
            "help": "The path to the directory that should contain the version.json file. The default is the root of the git repo."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "The initial version to set. The default is <c>1.0-beta</c>."
          },
          {
            "name": "Sources",
            "type": "List<string>",
            "format": "--source {value}",
            "separator": " ",
            "help": "The URI(s) of the NuGet package source(s) used to determine the latest stable version of the Nerdbank.GitVersioning package. This setting overrides all of the sources specified in the NuGet.Config files."
          }
        ]
      }
    },
    {
      "help": "Gets the version information for a project.",
      "postfix": "GetVersion",
      "returnType": "NerdbankGitVersioning",
      "definiteArgument": "get-version",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the current directory."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata {value}",
            "help": "Adds an identifier to the build metadata part of a semantic version."
          },
          {
            "name": "Format",
            "type": "NerdbankGitVersioningFormat",
            "format": "--format {value}",
            "help": "The format to write the version information. Allowed values are: <c>text</c>, <c>json</c>. The default is <c>text</c>."
          },
          {
            "name": "Variable",
            "type": "string",
            "format": "--variable {value}",
            "help": "The name of just one version property to print to stdout. When specified, the output is always in raw text. Useful in scripts."
          },
          {
            "name": "CommitIsh",
            "type": "string",
            "format": "-- {value}",
            "help": "The commit/ref to get the version information for. The default is <c>HEAD</c>."
          }
        ]
      }
    },
    {
      "help": "Updates the version stamp that is applied to a project.",
      "postfix": "SetVersion",
      "definiteArgument": "set-version",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the root directory of the repo that spans the current directory, or an existing version.json file, if applicable."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "-- {value}",
            "help": "The version to set."
          }
        ]
      }
    },
    {
      "help": "Creates a git tag to mark a version.",
      "postfix": "Tag",
      "definiteArgument": "tag",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the root directory of the repo that spans the current directory, or an existing version.json file, if applicable."
          },
          {
            "name": "VersionOrRef",
            "type": "string",
            "format": "-- {value}",
            "help": "The <c>a.b.c[.d]</c> version or git ref to be tagged. If not specified, <c>HEAD</c> is used."
          }
        ]
      }
    },
    {
      "help": "Gets the commit(s) that match a given version.",
      "postfix": "GetCommits",
      "definiteArgument": "get-commits",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the root directory of the repo that spans the current directory, or an existing version.json file, if applicable."
          },
          {
            "name": "Quiet",
            "type": "bool",
            "format": "--quiet",
            "help": "Use minimal output."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "-- {value}",
            "help": "The <c>a.b.c[.d]</c> version to find."
          }
        ]
      }
    },
    {
      "help": "Communicates with the ambient cloud build to set the build number and/or other cloud build variables.",
      "postfix": "Cloud",
      "definiteArgument": "cloud",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory used to calculate the version. The default is the current directory. Ignored if the <c>--version</c> option is specified."
          },
          {
            "name": "Metadata",
            "type": "string",
            "format": "--metadata {value}",
            "help": "Adds an identifier to the build metadata part of a semantic version."
          },
          {
            "name": "Version",
            "type": "string",
            "format": "--version {value}",
            "help": "The string to use for the cloud build number. If not specified, the computed version will be used."
          },
          {
            "name": "CISystem",
            "type": "NerdbankGitVersioningCISystem",
            "format": "--ci-system {value}",
            "help": "Force activation for a particular CI system. If not specified, auto-detection will be used."
          },
          {
            "name": "AllVars",
            "type": "bool",
            "format": "--all-vars",
            "help": "Defines ALL version variables as cloud build variables, with a <c>NBGV_</c> prefix."
          },
          {
            "name": "CommonVars",
            "type": "bool",
            "format": "--common-vars",
            "help": "Defines a few common version variables as cloud build variables, with a <c>Git</c> prefix (e.g. <c>GitBuildVersion</c>, <c>GitBuildVersionSimple</c>, <c>GitAssemblyInformationalVersion</c>)"
          },
          {
            "name": "Variables",
            "type": "Dictionary<string,string>",
            "format": "--define {value}",
            "itemFormat": "{key}={value}",
            "help": "Additional cloud build variables to define."
          }
        ]
      }
    },
    {
      "help": "Prepares a release by creating a release branch for the current version and adjusting the version on the current branch.",
      "postfix": "PrepareRelease",
      "definiteArgument": "prepare-release",
      "settingsClass": {
        "properties": [
          {
            "name": "Project",
            "type": "string",
            "format": "--project {value}",
            "help": "The path to the project or project directory. The default is the current directory."
          },
          {
            "name": "NextVersion",
            "type": "string",
            "format": "--nextVersion {value}",
            "help": " The version to set for the current branch. If omitted, the next version is determined automatically by incrementing the current version."
          },
          {
            "name": "VersionIncrement",
            "type": "string",
            "format": "--versionIncrement {value}",
            "help": "Overrides the 'versionIncrement' setting set in version.json for determining the next version of the current branch."
          },
          {
            "name": "Tag",
            "type": "string",
            "format": "-- {value}",
            "help": "The prerelease tag to apply on the release branch (if any). If not specified, any existing prerelease tag will be removed. The preceding hyphen may be omitted."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "NerdbankGitVersioningFormat",
      "values": [
        "Text",
        "Json"
      ]
    },
    {
      "name": "NerdbankGitVersioningCISystem",
      "values": [
        "AppVeyor",
        "VisualStudioTeamServices",
        "GitHubActions",
        "TeamCity",
        "AtlassianBamboo",
        "Jenkins",
        "GitLab",
        "Travis"
      ]
    }
  ]
}
