=== nuke-build/nuke/source/Nuke.CodeGeneration/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "title": "Tool metadata schema file by NUKE",
  "definitions": {
    "DataClass": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "noExtensionMethods": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "noArguments": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "name",
        "properties"
      ]
    },
    "Enumeration": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the enumeration.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "values": {
          "description": "The enumeration values.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "values"
      ]
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the property.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "type": {
          "description": "Type of the property. I.e., bool, int, string, List<int>, Dictionary<string, object>, Lookup<string, int.>",
          "type": "string"
        },
        "assertion": {
          "description": "Automatic assertion.",
          "type": "string",
          "enum": [
            "NotNull",
            "File",
            "Directory",
            "FileOrNull",
            "DirectoryOrNull"
          ]
        },
        "format": {
          "description": "Argument formatting for the property. '{value}' is replaced by the value of the property.",
          "type": "string"
        },
        "itemFormat": {
          "description": "Item formatting for dictionaries. '{key}' and '{value}' are replaced accordingly.",
          "type": "string"
        },
        "noArgument": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "customImpl": {
          "description": "Custom implementation of the property.",
          "type": "boolean"
        },
        "noExtensionMethod": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "separator": {
          "description": "Separator used for items of collection types.",
          "type": "string"
        },
        "disallowedCharacter": {
          "description": "Character that must be double-quoted.",
          "type": "string"
        },
        "quoteMultiple": {
          "description": "Specifies if list items should be double quoted.",
          "type": "boolean"
        },
        "default": {
          "description": "Default value that will be used if no value is given.",
          "type": "string"
        },
        "secret": {
          "description": "Specifies that the value is secret and should be hidden in output.",
          "type": "boolean"
        },
        "customValue": {
          "description": "Custom implementation of value presentation.",
          "type": "boolean"
        },
        "createOverload": {
          "description": "Specifies that an overload for the property should be created.",
          "type": "boolean"
        },
        "help": {
          "description": "Help text for the property.",
          "type": "string"
        },
        "delegates": {
          "description": "Dictionary delegates for named properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "SettingsClass": {
      "description": "The settings of the task.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the data class.",
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "baseClass": {
          "description": "The base class to inherit from.",
          "type": "string"
        },
        "noExtensionMethods": {
          "description": "Skips appendig of extension methods.",
          "type": "boolean"
        },
        "noArguments": {
          "description": "Omits argument parsing.",
          "type": "boolean"
        },
        "properties": {
          "description": "Properties of the data class.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Property"
          }
        }
      },
      "required": [
        "properties"
      ]
    },
    "Task": {
      "type": "object",
      "properties": {
        "help": {
          "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
          "type": "string"
        },
        "postfix": {
          "description": "Postfix for the task alias.",
          "type": "string",
          "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
        },
        "returnType": {
          "description": "Return type of the task.",
          "type": "string"
        },
        "omitCommonProperties": {
          "description": "Skips appending of common task properties.",
          "type": "boolean"
        },
        "customStart": {
          "description": "Custom start implementation.",
          "type": "boolean"
        },
        "customAssertion": {
          "description": "Custom process assertion implementation.",
          "type": "boolean"
        },
        "definiteArgument": {
          "description": "Argument that will always be printed independently of any set property.",
          "type": "string"
        },
        "settingsClass": {
          "$ref": "#/definitions/SettingsClass"
        }
      },
      "required": [
        "settingsClass"
      ]
    }
  },
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "license": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "references": {
      "description": "Contains all references on which this definition is based on. Allows checking for updates.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "name": {
      "description": "Name of the Tool.",
      "type": "string",
      "pattern": "^[A-Z][a-z]+(?:[A-Z0-9][a-z0-9]+)*$"
    },
    "officialUrl": {
      "description": "Url to the official website.",
      "type": "string",
      "format": "uri"
    },
    "help": {
      "description": "Help or introduction text to for the tool. Supports 'a-href', 'c', 'em', 'b', 'ul', 'li' and 'para' tags for better formatting.",
      "type": "string"
    },
    "packageId": {
      "description": "ID for the NuGet package.",
      "type": "string"
    },
    "packageExecutable": {
      "description": "Exact name of the main executable found in the './tools' folder. Case-sensitive.",
      "type": "string"
    },
    "environmentExecutable": {
      "description": "Exact name of the environment variable that contains the path to the executable.",
      "type": "string"
    },
    "pathExecutable": {
      "description": "Exact name of the executable that can be found via 'where' or 'which'.",
      "type": "string"
    },
    "customExecutable": {
      "description": "Defines that locating the executable is implemented customly.",
      "type": "boolean"
    },
    "tasks": {
      "description": "Help or introduction text to for the tool. Can contain HTML tags for better formatting.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "commonTaskProperties": {
      "description": "Common properties for all tasks.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Property"
      }
    },
    "dataClasses": {
      "description": "Common used data classes.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/DataClass"
      }
    },
    "enumerations": {
      "description": "Used enumerations.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Enumeration"
      }
    }
  },
  "required": [
    "name",
    "officialUrl",
    "tasks"
  ]
}

=== nuke-build/nuke/source/Nuke.Common/Tools/CMake/CMake.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "references": [
    "https://cmake.org/cmake/help/latest/manual/cmake.1.html"
  ],
  "name": "CMake",
  "officialUrl": "https://cmake.org/cmake/help/latest/manual/cmake.1.html",
  "help": "The cmake executable is the command-line interface of the cross-platform build system generator CMake.",
  "pathExecutable": "cmake",
  "tasks": [
    {
      "help": "Generates a build project using cmake.",
      "postfix": "Generate",
      "settingsClass": {
        "properties": [
          {
            "name": "Generator",
            "type": "CMakeGenerator",
            "format": "-G {value}",
            "default": "CMakeGenerator.Visual_Studio_16_2019",
            "help": "Specify the build system to generate."
          },
          {
            "name": "Platform",
            "type": "CMakePlatform",
            "format": "-A {value}",
            "default": "CMakePlatform.x64",
            "help": "Specify the platform to build for."
          },
          {
            "name": "RootDirectory",
            "type": "string",
            "format": "-S {value}",
            "default": "\".\"",
            "help": "Specify the root directory of the 'CMakeLists.txt' file."
          },
          {
            "name": "OutputDirectory",
            "type": "string",
            "format": "-B {value}",
            "default": "\"./out\"",
            "help": "Specify the configuration to use when running the install script."
          },
          {
            "name": "ToolChain",
            "type": "string",
            "format": "-DCMAKE_TOOLCHAIN_FILE:FILEPATH={value}",
            "help": "Specify the path to a toolchain file to use."
          }
        ]
      }
    },
    {
      "help": "Runs the `cmake --install` command on a project generated with cmake.",
      "postfix": "Install",
      "definiteArgument": "--install",
      "settingsClass": {
        "properties": [
          {
            "name": "RootDirectory",
            "type": "string",
            "format": "{value}",
            "default": "\".\"",
            "help": "Specify the root directory of the cmake install script."
          },
          {
            "name": "Configuration",
            "type": "CMakeConfiguration",
            "format": "--config {value}",
            "default": "CMakeConfiguration.Debug",
            "help": "Specify the root directory of the 'CMakeLists.txt' file."
          },
          {
            "name": "OutputDirectory",
            "type": "string",
            "format": "--prefix {value}",
            "help": "Specify the output directory of the install script."
          },
          {
            "name": "Component",
            "type": "string",
            "format": "--component {value}",
            "help": "Specify the component to install."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "CMakeGenerator",
      "values": [
        "Visual Studio 15 2017",
        "Visual Studio 16 2019",
        "Visual Studio 17 2022",
        "Ninja",
        "Xcode"
      ]
    },
    {
      "name": "CMakePlatform",
      "values": [
        "Win32",
        "x64",
        "ARM",
        "ARM64"
      ]
    },
    {
      "name": "CMakeConfiguration",
      "values": [
        "Debug",
        "RelWithDebInfo",
        "Release",
        "MinSizeRel"
      ]
    }
  ]
}

=== nuke-build/nuke/build/specifications/GitLink.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "license": [
    "Copyright Matthias Koch 2017.",
    "Distributed under the MIT License.",
    "https://github.com/nuke-build/tools/blob/master/LICENSE"
  ],
  "references": [
    "https://raw.githubusercontent.com/GitTools/GitLink/1520bf13cf35337a368aa0c960135c564e519fbf/src/GitLink/Program.cs"
  ],
  "name": "GitLink",
  "officialUrl": "https://github.com/GitTools/GitLink/",
  "help": "GitLink makes symbol servers obsolete which saves you both time with uploading source files with symbols and the user no longer has to specify custom symbol servers (such as symbolsource.org). The advantage of GitLink is that it is fully customized for Git. It also works with GitHub or BitBucket urls so it does not require a local git repository to work. This makes it perfectly usable in continuous integration servers such as Continua CI. Updating all the pdb files is very fast. A solution with over 85 projects will be handled in less than 30 seconds. When using GitLink, the user no longer has to specify symbol servers. The only requirement is to ensure the check the Enable source server support option in Visual Studio.",
  "packageId": "gitlink",
  "packageExecutable": "GitLink.exe",
  "tasks": [
    {
      "postfix": "2",
      "settingsClass": {
        "properties": [
          {
            "name": "SolutionDirectory",
            "type": "string",
            "format": "{value}",
            "help": "The directory containing the solution with the pdb files."
          },
          {
            "name": "RepositoryUrl",
            "type": "string",
            "format": "-u {value}",
            "help": "Url to remote git repository."
          },
          {
            "name": "File",
            "type": "string",
            "format": "-f {value}",
            "help": "Solution file name."
          },
          {
            "name": "Configuration",
            "type": "string",
            "format": "-c {value}",
            "help": "Name of the configuration, default value is 'Release'."
          },
          {
            "name": "Platform",
            "type": "string",
            "format": "-p {value}",
            "help": "Name of the platform, default value is 'AnyCPU'."
          },
          {
            "name": "BranchName",
            "type": "string",
            "format": "-b {value}",
            "help": "Name of the branch to use on the remote repository."
          },
          {
            "name": "LogFile",
            "type": "string",
            "format": "-l {value}",
            "help": "The log file to write to."
          },
          {
            "name": "CommitSha",
            "type": "string",
            "format": "-s {value}",
            "help": "The SHA-1 hash of the commit."
          },
          {
            "name": "PdbDirectory",
            "type": "string",
            "format": "-d {value}",
            "help": "The directory where pdb files exists, default value is the normal project output directory."
          },
          {
            "name": "UsePowershell",
            "type": "bool",
            "format": "-powershell",
            "help": "Use an indexing strategy that won't rely on SRCSRV http support, but use a powershell command for URL download instead."
          },
          {
            "name": "ErrorsAsWarnings",
            "type": "bool",
            "format": "-errorsaswarnings",
            "help": "Don't fail on errors, but treat them as warnings instead."
          },
          {
            "name": "SkipVerification",
            "type": "bool",
            "format": "-skipverify",
            "help": "Skip pdb verification in case it causes issues (it's a formality anyway)"
          },
          {
            "name": "Debug",
            "type": "bool",
            "format": "-debug",
            "help": "Enables debug mode with special dumps of msbuild."
          }
        ]
      }
    },
    {
      "postfix": "3",
      "settingsClass": {
        "properties": [
          {
            "name": "PdbFile",
            "type": "string",
            "format": "{value}",
            "help": "The PDB to add source indexing to."
          },
          {
            "name": "Method",
            "type": "GitLinkSourceCodeRetrieval",
            "format": "--method {value}",
            "help": "The method for SRCSRV to retrieve source code. One of &lt;Http|Powershell&gt;. Default is Http."
          },
          {
            "name": "RepositoryUrl",
            "type": "string",
            "format": "--url {value}",
            "help": "Url to remote git repository."
          },
          {
            "name": "CommitSha",
            "type": "string",
            "format": "--commit {value}",
            "help": "The git ref to assume all the source code belongs to."
          },
          {
            "name": "BaseDirectory",
            "type": "string",
            "format": "--baseDir {value}",
            "help": "The path to the root of the git repo."
          },
          {
            "name": "SkipVerification",
            "type": "bool",
            "format": "--skipVerify",
            "help": "Skip verification that all source files are available in source control."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "GitLinkSourceCodeRetrieval",
      "values": [
        "Http",
        "Powershell"
      ]
    }
  ]
}

=== nuke-build/nuke/build/specifications/WebConfigTransformRunner.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "license": [
    "Copyright Matthias Koch 2017.",
    "Distributed under the MIT License.",
    "https://github.com/nuke-build/tools/blob/master/LICENSE"
  ],
  "references": [
    "https://raw.githubusercontent.com/erichexter/WebConfigTransformRunner/master/Readme.md"
  ],
  "name": "WebConfigTransformRunner",
  "officialUrl": "https://github.com/erichexter/WebConfigTransformRunner",
  "help": "This is a commandline tool to run an ASP.Net web.config tranformation.",
  "packageId": "WebConfigTransformRunner",
  "packageExecutable": "WebConfigTransformRunner.exe",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "WebConfigFilename ",
            "type": "string",
            "assertion": "File",
            "format": "{value}",
            "help": "The base web.config file"
          },
          {
            "name": "TransformFilename",
            "type": "string",
            "assertion": "File",
            "format": "{value}",
            "help": "The transformation web.config file"
          },
          {
            "name": "OutputFilename",
            "type": "string",
            "assertion": "NotNull",
            "format": "{value}",
            "help": "The path to the output web.config file"
          }
        ]
      }
    }
  ]
}

=== nuke-build/nuke/build/specifications/MauiCheck.json
{
  "$schema": "https://raw.githubusercontent.com/nuke-build/nuke/master/source/Nuke.CodeGeneration/schema.json",
  "name": "MauiCheck",
  "officialUrl": "https://github.com/Redth/dotnet-maui-check",
  "help": "A dotnet tool for helping set up your .NET MAUI environment.",
  "packageId": "Redth.Net.Maui.Check",
  "packageExecutable": "MauiCheck.dll",
  "tasks": [
    {
      "settingsClass": {
        "properties": [
          {
            "name": "Manifest",
            "type": "string",
            "format": "--manifest {value}",
            "help": "Manifest files are currently used by the doctor to fetch the latest versions and requirements. The manifest is hosted by default at: <a href=\"https://aka.ms/dotnet-maui-check-manifest\">https://aka.ms/dotnet-maui-check-manifest</a>. Use this option to specify an alternative file path or URL to use."
          },
          {
            "name": "Fix",
            "type": "bool",
            "format": "--fix",
            "help": "You can try using the <c>--fix</c> argument to automatically enable solutions to run without being prompted."
          },
          {
            "name": "NonInteractive",
            "type": "bool",
            "format": "--non-interactive",
            "help": "If you're running on CI you may want to run without any required input with the <c>--non-interactive</c> argument. You can combine this with <c>--fix</c> to automatically fix without prompting."
          },
          {
            "name": "Preview",
            "type": "bool",
            "format": "--preview",
            "help": "This uses a more frequently updated manifest with newer versions of things more often. The manifest is hosted by default at: <a href=\"https://aka.ms/dotnet-maui-check-manifest-dev\">https://aka.ms/dotnet-maui-check-manifest-dev</a>"
          },
          {
            "name": "Ci",
            "type": "bool",
            "format": "--ci",
            "help": "Uses the <c>dotnet-install</c> powershell / bash scripts for installing the dotnet SDK version from the manifest instead of the global installer."
          },
          {
            "name": "Skip",
            "type": "List<MauiCheckCheckup>",
            "format": "--skip {value}",
            "help": "Skips a checkup by name or id as listed in maui-check list. NOTE: If there are any other checkups which depend on a skipped checkup, they will be skipped too."
          }
        ]
      }
    },
    {
      "postfix": "Config",
      "definiteArgument": "config",
      "settingsClass": {
        "properties": [
          {
            "name": "DotNetVersion",
            "type": "bool",
            "format": "--dotnet-version",
            "help": "Use the SDK version in the manifest in <em>global.json</em>."
          },
          {
            "name": "DotNetPrerelease",
            "type": "bool",
            "format": "--dotnet-pre {value}",
            "help": "Change the <c>allowPrerelease</c> value in the <em>global.json</em>."
          },
          {
            "name": "DotNetRollForward",
            "type": "MauiCheckDotNetRollForward",
            "format": "--dotnet-rollForward {value}",
            "help": "Change the <c>rollForward</c> value in <em>global.json</em> to one of the allowed values specified."
          },
          {
            "name": "NuGetSources",
            "type": "bool",
            "format": "--nuget-sources",
            "help": "Adds the nuget sources specified in the manifest to the <em>NuGet.config</em> and creates the file if needed."
          }
        ]
      }
    }
  ],
  "enumerations": [
    {
      "name": "MauiCheckDotNetRollForward",
      "values": [
        "disable",
        "major",
        "minor",
        "feature",
        "patch",
        "latestMajor",
        "latestMinor",
        "latestFeature",
        "latestPatch"
      ]
    },
    {
      "name": "MauiCheckCheckup",
      "values": [
        "OpenJdkCheckup",
        "VisualStudioMacCheckup",
        "AndroidSdkPackagesCheckup",
        "AndroidEmulatorCheckup",
        "XCodeCheckup",
        "DotNetCheckup",
        "DotNetWorkloadDuplicatesCheckup",
        "DotNetSentinelCheckup",
        "DotNetWorkloadsCheckup"
      ]
    }
  ]
}
